#!/bin/bash

SCRIPT=`realpath $0`
export ADLAMIN_HOME=`dirname $SCRIPT`

source $ADLAMIN_HOME/firewall/iptables.sh
source $ADLAMIN_HOME/network.sh
source $ADLAMIN_HOME/router.sh

create_network internal 172.19.0.0/24
create_router internal 172.19.0.2