#!/bin/bash

SCRIPT=`realpath $0`
export ADLAMIN_HOME=`dirname $SCRIPT`

source $ADLAMIN_HOME/firewall/iptables.sh
source $ADLAMIN_HOME/network.sh
source $ADLAMIN_HOME/router.sh

SERVICE=$1
URL=$2

cd $SERVICE
source .service

create_network $NETWORK $SUBNET
create_router $NETWORK $ROUTER_IP

forward_to_server dmz $NETWORK 172.18.0.2 $ROUTER_IP tcp 8080
forward_to_server $NETWORK $NETWORK $ROUTER_IP $SUBNET tcp $PORT

add_server dmz $URL $ROUTER_IP