#!/bin/bash

SCRIPT=$(realpath $0)
export ADLAMIN_HOME=`dirname $SCRIPT` || return

source $ADLAMIN_HOME/git.sh
source $ADLAMIN_HOME/docker.sh
source $ADLAMIN_HOME/router.sh

VERSION=$1

source .service

IMAGE=$PROJECT_NAME:$VERSION

clone $GIT_REPO TEMP_$PROJECT_NAME

cd TEMP_$PROJECT_NAME
docker_build $IMAGE
cd ..
rm -rf TEMP_$PROJECT_NAME

docker_stop $PROJECT_NAME

if test $IS_PERSISTENT -eq 1; then
IP=$(docker_run_with_persistence $IMAGE $PROJECT_NAME $NETWORK $PERSISTENCE_PATH)
echo "Container wp ip is $IP"
else
IP=$(docker_run $IMAGE $PROJECT_NAME $NETWORK)
echo "Container ip is $IP"
fi


add_route $NETWORK $IP $PORT

router_reload $NETWORK
