#!/bin/bash

source /usr/local/lib/adlamin/deploy.sh

set -o errtrace # Enable the err trap, code will get called when an error is detected
trap "echo ERROR: There was an error in ${FUNCNAME-main context}, details to follow" ERR

show_help() {
  echo "Usage:"
  echo "adlamin_create_service VERSION INTERFACE PROJECT_NAME GIT_REPO IS_PERSISTENT PERSISTENCE_PATH NETWORK"
  echo "---"
  echo "VERSION: Version of the deployed software"
  echo "INTERFACE: Network interface that receives the dmz traffic"
  echo "PROJECT_NAME: Name of the project"
  echo "GIT_REPO: The git repository path of the software to deploy"
  echo "IS_PERSISTENT: 0 to disable"
  echo "PERSISTENCE_PATH: Does not works"
  echo "NETWORK: Network name created by adlamin_create_service"
  echo "Example:"
  echo "adlamin_deploy 1.0.0 enp0s3 test https://github.com/calenicolas/dummy_server.git 0 0 test"
}

while getopts ":h" option; do
   # shellcheck disable=SC2220
   case $option in
      h) # display Help
         show_help
         exit;;
   esac
done

deploy $1 $2 $3 $4 $5 $6 $7