#!/bin/bash

#ARGS
INPUT_INTERFACE=$1
DESTINATION_PORT=$2
IP=$3

/usr/sbin/iptables -I INPUT_PORT_KNOCKING \
  -i $INPUT_INTERFACE \
  -s $IP \
  --dport $DESTINATION_PORT \
  -m STATE \
  --state NEW,ESTABLISHED \
  -j ACCEPT
  
/usr/sbin/iptables -I OUTPUT_PORT_KNOCKING \
  -i $INPUT_INTERFACE \
  -d $IP \
  --sport $DESTINATION_PORT \
  -m STATE \
  --state ESTABLISHED \
  -j ACCEPT
